### ISSUE TITLE
could not authenticate: user githubactions not entitled to use Docker Scout

### ISSUE THREAD

**Issue by davide-malagoli-ict-group-it** [docker/scout-action#11]
Why if I use 

```
- name: Analyze for critical and high CVEs
      id: docker-scout-cves
      uses: docker/scout-action@788bd7991dd23939af62db37c4b77ec009021e17
      with:
        command: cves
        image: ${{ steps.meta.outputs.tags }}
        sarif-file: sarif.output.json
        only-severities: critical,high
        only-fixed: true
        platform: "linux/arm64"
```

like in the repo

https://github.com/docker/scout-demo-service

https://github.com/docker/scout-demo-service/blob/main/.github/workflows/docker-build.yaml

everything seems to work fine, but if I use any other release (0.18,0.19,0.20)
it gives me this error?

> Error: could not authenticate: user githubactions not entitled to use Docker Scout

```
Run docker/scout-action@v0.[2](https://github.com/n-essio/scout-demo-service/actions/runs/5645918105/job/15292721485#step:7:2)0.0
  with:
    command: cves
    image: ghcr.io/n-essio/scout-demo-service:main
    sarif-file: sarif.output.json
    only-severities: critical,high
    only-fixed: true
    platform: linux/arm64
    summary: true
    github-token: ***
    write-comment: true
  env:
    REGISTRY: ghcr.io
    IMAGE_NAME: n-essio/scout-demo-service
    SHA: 
    DOCKERFILE_PATH: Dockerfile
    DOCKER_METADATA_OUTPUT_VERSION: main
    DOCKER_METADATA_OUTPUT_TAGS: ghcr.io/n-essio/scout-demo-service:main
    DOCKER_METADATA_OUTPUT_LABELS: org.opencontainers.image.title=scout-demo-service
  org.opencontainers.image.description=
  org.opencontainers.image.url=https://github.com/n-essio/scout-demo-service
  org.opencontainers.image.source=https://github.com/n-essio/scout-demo-service
  org.opencontainers.image.version=main
  org.opencontainers.image.created=202[3](https://github.com/n-essio/scout-demo-service/actions/runs/5645918105/job/15292721485#step:7:3)-07-2[4](https://github.com/n-essio/scout-demo-service/actions/runs/5645918105/job/15292721485#step:7:4)T14:11:[5](https://github.com/n-essio/scout-demo-service/actions/runs/5645918105/job/15292721485#step:7:5)0.873Z
  org.opencontainers.image.revision=cf1c7b17f72[6](https://github.com/n-essio/scout-demo-service/actions/runs/5645918105/job/15292721485#step:7:6)15121d4c9fb2f9b98bfef0b04306
  org.opencontainers.image.licenses=
  org.opencontainers.image.revision=
  com.docker.image.source.entrypoint=Dockerfile
    DOCKER_METADATA_OUTPUT_JSON: {"tags":["ghcr.io/n-essio/scout-demo-service:main"],"labels":{"org.opencontainers.image.title":"scout-demo-service","org.opencontainers.image.description":"","org.opencontainers.image.url":"https://github.com/n-essio/scout-demo-service","org.opencontainers.image.source":"https://github.com/n-essio/scout-demo-service","org.opencontainers.image.version":"main","org.opencontainers.image.created":"2023-0[7](https://github.com/n-essio/scout-demo-service/actions/runs/5645918105/job/15292721485#step:7:7)-24T14:11:50.[8](https://github.com/n-essio/scout-demo-service/actions/runs/5645918105/job/15292721485#step:7:8)73Z","org.opencontainers.image.revision":"","org.opencontainers.image.licenses":"","com.docker.image.source.entrypoint":"Dockerfile"}}
    DOCKER_METADATA_OUTPUT_BAKE_FILE: /tmp/docker-actions-toolkit-yKofRp/docker-metadata-action-bake.json
Error: could not authenticate: user githubactions not entitled to use Docker Scout
```

Someone managed to get it work?
