### ISSUE TITLE
0.23.2 - panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ryancammer** [docker/scout-action#14]
I upgraded to 0.23.2, and now get the following when I run the following action:

```

      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@v0.23.2
        with:
          command: quickview,cves,compare
          image: ${{ steps.extract-tag.outputs.first_tag }}
          to: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:master
          ignore-unchanged: true
          write-comment: false
          sarif-file: sarif.output.json
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf9ece6]

goroutine 1 [running]:
github.com/docker/scout-cli-plugin/internal/configuration.(*Configuration).List(0x0)
	/home/runner/work/scout-cli-plugin/scout-cli-plugin/internal/configuration/configuration.go:47 +0x26
github.com/docker/scout-cli-plugin/internal/configuration.(*Configuration).Get(0x30?, {0x1f5ad57, 0xc})
	/home/runner/work/scout-cli-plugin/scout-cli-plugin/internal/configuration/configuration.go:69 +0x93
github.com/docker/scout-cli-plugin/internal/configuration.Get(...)
	/home/runner/work/scout-cli-plugin/scout-cli-plugin/internal/configuration/configuration.go:75
github.com/docker/scout-cli-plugin/organization.Select({0xc0000480c0?, 0xc000a7fda0?})
	/home/runner/work/scout-cli-plugin/scout-cli-plugin/organization/context.go:34 +0x37
github.com/docker/scout-cli-plugin/organization.Store({0x[28](https://github.com/[redacted]/[redacted]/actions/runs/6009338742/job/16298562690?pr=12700#step:10:29)632b0, 0xc000aaec[30](https://github.com/snap-mobile/raise/actions/runs/6009338742/job/16298562690?pr=12700#step:10:31)}, {0xc0000480c0?, 0x38e6[34](https://github.com/[redacted]/[redacted]/actions/runs/6009338742/job/16298562690?pr=12700#step:10:35)0?})
	/home/runner/work/scout-cli-plugin/scout-cli-plugin/organization/context.go:23 +0x28
main.run()
	/home/runner/work/scout-cli-plugin/scout-cli-plugin/cmd/github-action/main.go:64 +0x289
main.main()
	/home/runner/work/scout-cli-plugin/scout-cli-plugin/cmd/github-action/main.go:83 +0x13
```

I don't know what else to tell you other than that I'm not doing anything wild. I was forced to log into docker, which is new. I'm not thrilled about that, but fine.
