### ISSUE TITLE
`command: compare` with `sbom://`

### ISSUE THREAD

**Issue by MPV** [docker/scout-action#43]
I'd like to be able to use the new `sbom://` syntax, but it seems it's not (yet) supported with the `command: compare` mode.

Steps to reproduce:
1. Run a workflow with a step like this:

```yaml
      - name: Generate SBOM for image
        id: sbom
        uses: anchore/sbom-action@719133684c7d294116626d1344fe64f0d2ff3e9e # v0.15.2
        with:
          image: ${{ env.IMAGE }}:${{ github.sha }}
          output-file: sbom.spdx.json

      - name: Docker Scout
        if: ${{ github.event_name == 'pull_request' && !cancelled() }}
        uses: docker/scout-action@c01629436921e4c567967cbfa14764f4b6113237 # v1.6.4
        with:
          command: compare
          image: sbom://sbom.spdx.json
          to: ${{ env.IMAGE }}:latest
          ignore-unchanged: true
          only-fixed: true
          write-comment: true
```

Expected results:
1. Same kind of output as in my non-SBOM example below.

Actual results:
1. The step fails with `Error: missing or wrong "image" input`

---

non-SBOM example (for comparison):

```yaml
      - name: Docker Scout
        if: ${{ github.event_name == 'pull_request' && !cancelled() }}
        uses: docker/scout-action@c01629436921e4c567967cbfa14764f4b6113237 # v1.6.4
        with:
          command: compare
          image: ${{ env.IMAGE }}:${{ github.sha }}
          to: ${{ env.IMAGE }}:latest
          ignore-unchanged: true
          only-fixed: true
          write-comment: true
```

For reference, this should be supported upstream nowadays, as per:
- https://github.com/docker/scout-cli/issues/97

And here's using it without the action:
```shell
$ syft alpine:latest -o syft-json > sbom.spdx.json
$ docker scout compare --to alpine:latest sbom://sbom.spdx.json
[...]
```
