### ISSUE TITLE
Compare to Repo: Unable to Parse Repo URL

### ISSUE THREAD

**Issue by oliv10** [docker/scout-action#7]
# Desc
I get this error when trying to compare my image to the latest released version.

# Error

`Error: could not get the image ghcr.io/Org/Repo:latest: failed to parse reference ghcr.io/Org/Repo:latest: could not parse reference: ghcr.io/Org/Repo:latest`

I believe the issue has to do with the name of the Github Organization and or Repo having capital letters in them.

When I tried to run the step with the _**to:**_ flag being all lowercase characters instead of using _**ghcr.io/${{github.repository}}**_ (which could return capital letters depending on the name of the User/Org and Repo) it worked without issue.

# Job Step (Not Working)

```
- name: Docker Scout Recommendations
  id: docker-scout-recs
  if: ${{ github.event_name == 'pull_request' }}
  uses: docker/scout-action@v0.18.1
  with:
    command: recommendations,compare
    image: ${{ steps.meta.outputs.tags }}
    to: ghcr.io/${{ github.repository }}:latest
    write-comment: true
    github-token: ${{ secrets.GITHUB_TOKEN }}
```

I'd expect the above to work every time but since my org and repo name include capital letters it throws the error stated. 

# Job Step (Working)

```
- name: Docker Scout Recommendations
  id: docker-scout-recs
  if: ${{ github.event_name == 'pull_request' }}
  uses: docker/scout-action@v0.18.1
  with:
    command: recommendations,compare
    image: ${{ steps.meta.outputs.tags }}
    # lowercase characters ONLY in repo url
    to: ghcr.io/org-or-user/repo:latest
    write-comment: true
    github-token: ${{ secrets.GITHUB_TOKEN }}
```

# Recommendation

My recommendation would be to convert the _**to:**_ flag to all lowercase characters before it attempts to pull the repo.

**Comment by mcapell** [comment]
Thanks for reporting this @oliv10, we will have a look

**Comment by cdupuis** [comment]
@oliv10 with the latest release of this action, this should be fixed. Please gives this a try.

**Comment by oliv10** [comment]
Without changing anything in my step other than the version I now get an authentication error.

`Error: could not authenticate: user githubactions not entitled to use Docker Scout`

# Step

```
-       name: Docker Scout Recommendations
        id: docker-scout-recs
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/scout-action@v0.19.0
        with:
          # command: compare,recommendations
          command: recommendations
          image: ${{ steps.meta.outputs.tags }}
          # Will change back once bug has been fixed by Docker Team
          # to: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          # to: ${{ env.REGISTRY }}/shield-cyber/openvas-rest-api:latest
          write-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
```
