### ISSUE TITLE
Version 0.19.0 Authentication Issue

### ISSUE THREAD

**Issue by oliv10** [docker/scout-action#8]
# Desc

Unable to run the action in its basic state because it fails to authenticate.

# Bug

`Error: could not authenticate: user githubactions not entitled to use Docker Scout`

# Job Step

```
-       name: Docker Scout Recommendations
        id: docker-scout-recs
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/scout-action@v0.19.0
        with:
          command: recommendations
          image: ${{ steps.meta.outputs.tags }}
          write-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

# Recommendation

IDK guys I can't see the source code. But I can tell you that this works fine in v0.18.1 and in [this commit](https://github.com/docker/scout-action/tree/1889e56711e187a213c163029023456f451a8357).
